@c
@c  COPYRIGHT (c) 1988-1998.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.
@c
@c  $Id$
@c

@ifinfo
@node Preface, General, Top, Top
@end ifinfo

@unnumbered Preface

This document lists the functions, constant, macros, feature flags,
and types defined in the POSIX 1003.1 standard.  Each section in 
this document corresponds to a section in the 1003.1 standard
and the implementation status of the items required by the standard
are listed.

