\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename porting.info
@setcontentsaftertitlepage
@syncodeindex vr fn
@synindex ky cp
@paragraphindent 0
@c %**end of header

@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@c
@c   Master file for the Porting Guide
@c

@c Joel's Questions
@c
@c  1.  Why does paragraphindent only impact makeinfo?
@c  2.  Why does paragraphindent show up in HTML?
@c

@include version.texi
@include common/setup.texi
@include common/rtems.texi

@ifset use-ascii
@dircategory RTEMS On-Line Manual
@direntry
* RTEMS Porting Guide: (porting).      The Porting Guide
@end direntry
@end ifset

@c variable substitution info:
@c
@set is-C
@clear is-Ada
@set LANGUAGE C
@set STRUCTURE structure
@set ROUTINE function
@set OR |
@set RPREFIX RTEMS_
@set DIRPREFIX rtems_
@c the language is @value{LANGUAGE}
@c NOTE:  don't use underscore in the name
@c

@c
@c  Title Page Stuff
@c






@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage RTEMS Porting Guide

@setchapternewpage odd
@settitle RTEMS Porting Guide
@titlepage
@finalout

@title RTEMS Porting Guide
@subtitle Edition @value{EDITION}, for RTEMS @value{VERSION}
@sp 1
@subtitle @value{UPDATED}
@author On-Line Applications Research Corporation
@page
@include common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@contents

@include preface.texi
@include developtools.texi
@include sourcecode.texi
@include cpumodels.texi
@include cpuinit.texi
@include interrupts.texi
@include taskcontext.texi
@include idlethread.texi
@include prioritybitmap.texi
@include codetuning.texi
@include miscellaneous.texi
@node Top, Preface, (dir), (dir)
@top RTEMS Porting Guide

@menu
* Preface::
* Development Tools::
* Source Code Organization::
* CPU Model Variations::
* CPU Initialization::
* Interrupts::
* Task Context Management::
* IDLE Thread::
* Priority Bitmap Manipulation::
* Code Tuning Parameters::
* Miscellaneous::
* Command and Variable Index::
* Concept Index::
@end menu

@node Command and Variable Index, Concept Index, Miscellaneous Endian Swap Unsigned Integers, Top
@unnumbered Command and Variable Index

There are currently no Command and Variable Index entries.

@c @printindex fn

@node Concept Index, , Command and Variable Index, Top
@unnumbered Concept Index

There are currently no Concept Index entries.
@c @printindex cp

@bye

