@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@node Preface, Development Tools, Top, Top
@unnumbered Preface

The purpose of this manual is to provide a roadmap to those people porting
RTEMS to a new CPU family. This process includes a variety of activities
including the following:

@itemize @bullet

@item targeting the GNU development tools

@item porting the RTEMS executive code

@item developing a Board Support Package

@item writing an RTEMS CPU Supplement manual for the completed port.

@end itemize

This document focuses on the process of actually porting the RTEMS
executive code proper.  Each of the data structures, routines, and macro
definitions required of a port of RTEMS is described in this document.

Porting any operating system, including RTEMS, requires knowledge of the
operating system, target CPU architecture, and debug environment.  It is
very desirable to have a CPU simulator or hardware emulator when debugging
the port.  This manual assumes that the user is familiar with building and
using RTEMS, the C programming language, and the target CPU architecture.  
It is desirable to be familiar with the assembly language for the target
CPU family but since only a limited amount of assembly is required to port
RTEMS.

