\input ../texinfo/texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename FAQ
@syncodeindex vr fn
@synindex ky cp
@paragraphindent 0
@c @smallbook
@c %**end of header

@c
@c  COPYRIGHT (c) 1988-1998.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.
@c
@c  $Id$
@c

@c
@c   Master file for the RTEMS FAQ
@c

@include ../common/setup.texi

@ignore
@ifinfo
@format
START-INFO-DIR-ENTRY
* RTEMS Frequently Asked Questions (FAQ):
END-INFO-DIR-ENTRY
@end format
@end ifinfo
@end ignore

@c
@c  Title Page Stuff
@c

@set edition @value{RTEMS-EDITION}
@set version @value{RTEMS-VERSION}
@set update-date @value{RTEMS-UPDATE-DATE}
@set update-month @value{RTEMS-UPDATE-MONTH}

@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage RTEMS Frequently Asked Questions

@setchapternewpage odd
@settitle RTEMS Frequently Asked Questions
@titlepage
@finalout

@title RTEMS Frequently Asked Questions
@subtitle Edition @value{edition}, for @value{version}
@sp 1
@subtitle @value{update-month}
@author On-Line Applications Research Corporation
@page
@include ../common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@include basic.texi
@include tools.texi
@include concepts.texi
@include debug.texi
@include freesw.texi
@include embeddedinfo.texi
@include hwdebugaids.texi

@ifinfo
@node Top, Basic Information, (dir), (dir)
@top FAQ

This document is the RTEMS FAQ.  FAQ is an acronym for Frequently
Asked Questions and we sincerely hope that this contains the answers
to some of the questions most frequently asked about RTEMS.

Common questions have been divided into the following categories. 


@menu
* Basic Information::
* General Development Tool Hints::
* RTEMS Concepts::
* Debugging Hints::
* Free Software that Works with RTEMS::
* Resources for Embedded Information::
* Hardware to Ease Debugging::
@end menu

@c * Command and Variable Index::
@c * Concept Index::
@end ifinfo
@c 
@c 
@c Need to copy the emacs stuff and "trailer stuff" (index, toc) into here
@c

@c @node Command and Variable Index, Concept Index, Installing EGCS AND NEWLIB, Top
@c @unnumbered Command and Variable Index

@c There are currently no Command and Variable Index entries.

@c @printindex fn

@c @node Concept Index, , Command and Variable Index, Top
@c @unnumbered Concept Index

@c There are currently no Concept Index entries.
@c @printindex cp

@contents
@bye

