\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename posix_users.info
@setcontentsaftertitlepage
@syncodeindex vr fn
@synindex ky cp
@paragraphindent 0
@c %**end of header

@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@c
@c   Master file for the POSIX API User's Guide
@c

@c Joel's Questions
@c
@c  1.  Why does paragraphindent only impact makeinfo?
@c  2.  Why does paragraphindent show up in HTML?
@c

@include version.texi
@include common/setup.texi
@include common/rtems.texi

@ifset use-ascii
@dircategory RTEMS On-Line Manual
@direntry
* RTEMS Posix API User's Guide: (posix_users).
                                       Posix API User's Guide Plan
@end direntry
@end ifset

@c variable substitution info:
@c
@c Note: At the moment we do not document the Ada interface but by building
@c       in the infrastructure Florist support should be simple to add.
@set is-C
@clear is-Ada
@set LANGUAGE C
@set STRUCTURE structure
@set ROUTINE function
@set OR |
@set RPREFIX RTEMS_
@set DIRPREFIX rtems_
@c the language is @value{LANGUAGE}
@c NOTE:  don't use underscore in the name
@c

@c
@c  Title Page Stuff
@c

@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage RTEMS POSIX API User's Guide

@setchapternewpage odd
@settitle RTEMS POSIX API User's Guide
@titlepage
@finalout

@title RTEMS POSIX API User's Guide
@subtitle Edition @value{EDITION}, for RTEMS @value{VERSION}
@sp 1
@subtitle @value{UPDATED}
@author On-Line Applications Research Corporation
@page
@include common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@contents

@include preface.texi
@include process.texi
@include signal.texi
@include procenv.texi
@include files.texi
@include io.texi
@include device.texi
@include cspecific.texi
@include systemdb.texi
@include semaphores.texi
@include mutex.texi
@include cond.texi
@include memorymgmt.texi
@include sched.texi
@include clock.texi
@include timer.texi
@include message.texi
@include thread.texi
@include key.texi
@include cancel.texi
@include libc.texi
@include libm.texi
@include status.texi
@node Top, Preface, (dir), (dir)
@top RTEMS POSIX API User's Guide

@menu
* Preface::
* Process Creation and Execution Manager::
* Signal Manager::
* Process Environment Manager::
* Files and Directories Manager::
* Input and Output Primitives Manager::
* Device- and Class- Specific Functions Manager::
* Language-Specific Services for the C Programming Language Manager::
* System Databases Manager::
* Semaphore Manager::
* Mutex Manager::
* Condition Variable Manager::
* Memory Management Manager::
* Scheduler Manager::
* Clock Manager::
* Timer Manager::
* Message Passing Manager::
* Thread Manager::
* Key Manager::
* Thread Cancellation Manager::
* Services Provided by C Library (libc)::
* Services Provided by the Math Library (libm)::
* Status of Implementation::
* Command and Variable Index::
* Concept Index::
@end menu

@node Command and Variable Index, Concept Index, , Top
@unnumbered Command and Variable Index

@c There are currently no Command and Variable Index entries.

@printindex fn

@node Concept Index, , Command and Variable Index, Top
@unnumbered Concept Index

@c There are currently no Concept Index entries.
@printindex cp

@bye

