\input ../texinfo/texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename posix_users
@syncodeindex vr fn
@synindex ky cp
@paragraphindent 0
@c @smallbook
@c %**end of header

@c
@c  COPYRIGHT (c) 1988-1998.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.
@c
@c  $Id$
@c

@c
@c   Master file for the C User's Guide
@c

@c Joel's Questions
@c
@c  1.  Why does paragraphindent only impact makeinfo?
@c  2.  Why does paragraphindent show up in HTML?
@c

@include ../common/setup.texi

@ignore
@ifinfo
@format
START-INFO-DIR-ENTRY
* RTEMS Posix API User's Guide: (posix_users).   Posix API User's Guide Plan
END-INFO-DIR-ENTRY
@end format
@end ifinfo
@end ignore

@c variable substitution info:
@c
@c @set LANGUAGE C
@c the language is @value{LANGUAGE}
@c NOTE:  don't use underscore in the name
@c

@c
@c  Title Page Stuff
@c

@set edition @value{RTEMS-EDITION}
@set version @value{RTEMS-VERSION}
@set update-date @value{RTEMS-UPDATE-DATE}
@set update-month @value{RTEMS-UPDATE-MONTH}

@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage RTEMS POSIX API User's Guide

@setchapternewpage odd
@settitle RTEMS POSIX API User's Guide 
@titlepage
@finalout

@title RTEMS POSIX API User's Guide
@subtitle Edition @value{edition}, for RTEMS @value{version}
@sp 1
@subtitle @value{update-month}
@author On-Line Applications Research Corporation
@page
@include ../common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@include preface.texi
@include thread.texi
@include signal.texi
@include mutex.texi
@include cond.texi
@include key.texi
@include clock.texi
@include sched.texi
@ifinfo
@node Top, Preface, (dir), (dir)
@top posix_users

This is the online version of the RTEMS POSIX API User's Guide

@menu
* Preface::
* Thread Manager::
* Signal Manager::
* Mutex Manager::
* Condition Variable Manager::
* Key Manager::
* Clock Manager::
* Scheduler Manager::
* Command and Variable Index::
* Concept Index::
@end menu

@end ifinfo
@c 
@c 
@c Need to copy the emacs stuff and "trailer stuff" (index, toc) into here
@c

@node Command and Variable Index, Concept Index, sched_yield, Top
@unnumbered Command and Variable Index

There are currently no Command and Variable Index entries.

@c @printindex fn

@node Concept Index, , Command and Variable Index, Top
@unnumbered Concept Index

There are currently no Concept Index entries.
@c @printindex cp

@contents
@bye

