@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@node Preface, , Top, Top
@unnumbered Preface

This is the User's Guide for the POSIX API support 
provided in RTEMS.

The functionality described in this document is based 
on the following standards:

@itemize @bullet

@item POSIX 1003.1b-1993.

@item POSIX 1003.1h/D3.

@item Open Group Single UNIX Specification.

@end itemize

Much of the POSIX API standard is actually implemented in the
Cygnus Newlib ANSI C Library.  Please refer to documentation on
Newlib for more information on the functionality it supplies.

This manual is still under construction and improvements
are welcomed from users.

@unnumberedsec Acknowledgements

@include common/opengroup_preface_acknowledgement.texi

