@c
@c  COPYRIGHT (c) 1988-1998.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.
@c
@c  $Id$
@c

@ifinfo
@node Preface, Thread Manager, Top, Top
@end ifinfo
@unnumbered Preface

This is the user's guide for the POSIX API support for RTEMS.

We intend for this manual to only be a listing of the API.  Please
refer to the ISO/IEC 9945-1 @i{Information Technology -
Portable Operating System Interface (POSIX) - Part 1: System
Application Program Interface (API) [C Language]} for the specific
functionality and behavior of the services.

In addition, much of the POSIX API standard is actually implemented
in the newlib ANSI C Library.  Please refer to documentation on
newlib for more information on what it supplies.
