@c
@c  COPYRIGHT (c) 1988-2002.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.
@c
@c  $Id$
@c

@ifinfo
@node Preface, , Top, Top
@end ifinfo
@unnumbered Preface

This is the User's Guide for the POSIX API support 
provided in RTEMS.

The functionality described in this document is based 
on the following standards:

@itemize @bullet

@item POSIX 1003.1b-1993.

@item POSIX 1003.1h/D3.

@end itemize

Much of the POSIX API standard is actually implemented in the
Cygnus Newlib ANSI C Library.  Please refer to documentation on
Newlib for more information on what it supplies.

At this point, this is just beginning to become what it 
ultimately should be.

