#define ap_st_n __fpsp_ap_st_n
#define ap_st_z __fpsp_ap_st_z
#define b1238_fix __fpsp_b1238_fix
#define BIGRN __fpsp_BIGRN
#define BIGRP __fpsp_BIGRP
#define BIGRZRM __fpsp_BIGRZRM
#define bindec __fpsp_bindec
#define binstr __fpsp_binstr
#define calc_e __fpsp_calc_e
#define calc_m __fpsp_calc_m
#define decbin __fpsp_decbin
#define denorm __fpsp_denorm
#define dest_dbl __fpsp_dest_dbl
#define dest_ext __fpsp_dest_ext
#define dest_sgl __fpsp_dest_sgl
#define dnrm_lp __fpsp_dnrm_lp
#define do_func __fpsp_do_func
#define dst_nan __fpsp_dst_nan
#define fpsp_bsun __fpsp_fpsp_bsun
#define fpsp_done __fpsp_fpsp_done
#define fpsp_fline __fpsp_fpsp_fline
#define fpsp_fmt_error __fpsp_fpsp_fmt_error
#define fpsp_operr __fpsp_fpsp_operr
#define fpsp_ovfl __fpsp_fpsp_ovfl
#define fpsp_snan __fpsp_fpsp_snan
#define fpsp_unfl __fpsp_fpsp_unfl
#define fpsp_unimp __fpsp_fpsp_unimp
#define fpsp_unsupp __fpsp_fpsp_unsupp
#define g_dfmtou __fpsp_g_dfmtou
#define gen_except __fpsp_gen_except
#define get_fline __fpsp_get_fline
#define get_op __fpsp_get_op
#define g_opcls __fpsp_g_opcls
#define g_rndpr __fpsp_g_rndpr
#define ld_minf __fpsp_ld_minf
#define ld_mone __fpsp_ld_mone
#define ld_mpi2 __fpsp_ld_mpi2
#define ld_mzero __fpsp_ld_mzero
#define ld_pinf __fpsp_ld_pinf
#define ld_pone __fpsp_ld_pone
#define ld_ppi2 __fpsp_ld_ppi2
#define ld_pzero __fpsp_ld_pzero
#define mem_read __fpsp_mem_read
#define mem_write __fpsp_mem_write
#define norm __fpsp_norm
#define nrm_set __fpsp_nrm_set
#define nrm_zero __fpsp_nrm_zero
#define ovf_res __fpsp_ovf_res
#define ovf_r_k __fpsp_ovf_r_k
#define ovf_r_x2 __fpsp_ovf_r_x2
#define ovf_r_x3 __fpsp_ovf_r_x3
#define PIRN __fpsp_PIRN
#define PIRP __fpsp_PIRP
#define PIRZRM __fpsp_PIRZRM
#define PITBL __fpsp_PITBL
#define pmod __fpsp_pmod
#define p_move __fpsp_p_move
#define prem __fpsp_prem
#define pscale __fpsp_pscale
#define PTENRM __fpsp_PTENRM
#define PTENRN __fpsp_PTENRN
#define PTENRP __fpsp_PTENRP
#define pwrten __fpsp_pwrten
#define real_bsun __fpsp_real_bsun
#define real_fline __fpsp_real_fline
#define real_inex __fpsp_real_inex
#define real_operr __fpsp_real_operr
#define real_ovfl __fpsp_real_ovfl
#define real_snan __fpsp_real_snan
#define real_trace __fpsp_real_trace
#define real_unfl __fpsp_real_unfl
#define real_unsupp __fpsp_real_unsupp
#define reg_dest __fpsp_reg_dest
#define res_func __fpsp_res_func
#define round __fpsp_round
#define sacos __fpsp_sacos
#define sacosd __fpsp_sacosd
#define sasin __fpsp_sasin
#define sasind __fpsp_sasind
#define satan __fpsp_satan
#define satand __fpsp_satand
#define satanh __fpsp_satanh
#define satanhd __fpsp_satanhd
#define sc_mul __fpsp_sc_mul
#define scos __fpsp_scos
#define scosd __fpsp_scosd
#define scosh __fpsp_scosh
#define scoshd __fpsp_scoshd
#define serror __fpsp_serror
#define setox __fpsp_setox
#define setoxd __fpsp_setoxd
#define setoxm1 __fpsp_setoxm1
#define setoxm1d __fpsp_setoxm1d
#define setoxm1i __fpsp_setoxm1i
#define sgetexp __fpsp_sgetexp
#define sgetexpd __fpsp_sgetexpd
#define sgetman __fpsp_sgetman
#define sgetmand __fpsp_sgetmand
#define sinf __fpsp_sinf
#define sint __fpsp_sint
#define sintd __fpsp_sintd
#define sintdo __fpsp_sintdo
#define sintrz __fpsp_sintrz
#define slog10 __fpsp_slog10
#define slog10d __fpsp_slog10d
#define slog2 __fpsp_slog2
#define slog2d __fpsp_slog2d
#define slogn __fpsp_slogn
#define slognd __fpsp_slognd
#define slognp1 __fpsp_slognp1
#define slognp1d __fpsp_slognp1d
#define SMALRN __fpsp_SMALRN
#define SMALRP __fpsp_SMALRP
#define SMALRZRM __fpsp_SMALRZRM
#define smod __fpsp_smod
#define smovcr __fpsp_smovcr
#define snzrinx __fpsp_snzrinx
#define sone __fpsp_sone
#define sopr_inf __fpsp_sopr_inf
#define spi_2 __fpsp_spi_2
#define src_nan __fpsp_src_nan
#define srem __fpsp_srem
#define sscale __fpsp_sscale
#define ssin __fpsp_ssin
#define ssincos __fpsp_ssincos
#define ssincosd __fpsp_ssincosd
#define ssincosi __fpsp_ssincosi
#define ssincosnan __fpsp_ssincosnan
#define ssincosz __fpsp_ssincosz
#define ssind __fpsp_ssind
#define ssinh __fpsp_ssinh
#define ssinhd __fpsp_ssinhd
#define sslog10 __fpsp_sslog10
#define sslog10d __fpsp_sslog10d
#define sslog2 __fpsp_sslog2
#define sslog2d __fpsp_sslog2d
#define sslogn __fpsp_sslogn
#define sslognd __fpsp_sslognd
#define sslognp1 __fpsp_sslognp1
#define stan __fpsp_stan
#define stand __fpsp_stand
#define stanh __fpsp_stanh
#define stanhd __fpsp_stanhd
#define stentox __fpsp_stentox
#define stentoxd __fpsp_stentoxd
#define sto_cos __fpsp_sto_cos
#define store __fpsp_store
#define sto_res __fpsp_sto_res
#define stwotox __fpsp_stwotox
#define stwotoxd __fpsp_stwotoxd
#define szero __fpsp_szero
#define szr_inf __fpsp_szr_inf
#define t_avoid_unsupp __fpsp_t_avoid_unsupp
#define tblpre __fpsp_tblpre
#define t_dz __fpsp_t_dz
#define t_dz2 __fpsp_t_dz2
#define t_extdnrm __fpsp_t_extdnrm
#define t_frcinx __fpsp_t_frcinx
#define t_inx2 __fpsp_t_inx2
#define t_operr __fpsp_t_operr
#define t_ovfl __fpsp_t_ovfl
#define t_ovfl2 __fpsp_t_ovfl2
#define t_resdnrm __fpsp_t_resdnrm
#define t_unfl __fpsp_t_unfl
#define unf_sub __fpsp_unf_sub
#define uni_2 __fpsp_uni_2
#define uni_getop __fpsp_uni_getop
#define uns_getop __fpsp_uns_getop
