@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.



@node RTEMS PROBLEM REPORT, Command and Variable Index, RTEMS Problem Reporting, Top
@chapter RTEMS PROBLEM REPORT

@example

Customer (Company) Name:

Customer Address:

Contact Name:

Telephone Voice:                         Fax:



Product:                                 Version:

Target Processor:                        Target System:

Host Computer System:

Host Operating System:                   Version:



Report Type:                    Customer Impact:



[ ] Problem/Error               [ ] System is inoperable, cannot proceed

[ ] Enhancement                 [ ] Must be corrected in the near future

[ ] Inquiry Suggestion          [ ] Problem may be avoided until fixed

[ ] Other______________         [ ] Problem is not time critical

                                [ ] Minor problem

@end example


Please provide a detailed description of the
problem (Attachments including source code, example code,
makefiles, possible solutions, and any other information
describing the problem will be appreciated):




