@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@node Development Environment Status, Development Environment Status RTEMS Executive Status, Installation Procedure Installing RTEMS, Top
@chapter Development Environment Status
@menu
* Development Environment Status RTEMS Executive Status::
* Development Environment Status Development Environment Status::
* Development Environment Status Known Problems::
@end menu

This chapter will describe the current status of
release version @value{VERSION} of the RTEMS Development Environment.

@node Development Environment Status RTEMS Executive Status, Development Environment Status Development Environment Status, Development Environment Status, Development Environment Status
@section RTEMS Executive Status

Release @value{VERSION} of the RTEMS Executive contains support
for both the classic RTEMS API based on the RTEID specification as well
as support for POSIX threads and real-time extensions.

The classic RTEMS API has the following managers based upon the RTEID
specification:

@itemize @bullet
@item Task
@item Initialization
@item Clock
@item Timer
@item Interrupt
@item Fatal Error
@item Message
@item Semaphore
@item Event
@item Signal
@item Region
@item Partition
@item Dual Ported Memory
@item I/O
@item Multiprocessing
@item Rate Monotonic
@item User Extensions
@end itemize

RTEMS also has support for the following managers based upon the POSIX threads
and real-time extensions:

@itemize @bullet
@item Thread
@item Clock
@item Key
@item Condition Variable
@item Mutex
@item Signal 
@item Scheduler
@end itemize

This release of the C implementation supports the
following processors and target boards:

@itemize @bullet
@item Motorola M68k family
@itemize -
@item DY-4 DMV152, SVME153
@item Motorola IDP
@item Motorola MVME135, MVME136
@item Motorola MVME147, MVME147S
@item Motorola MVME162
@item EFI 68000 and 68332
@item Generic 68302
@item Generic 68360 and 68360 in companion mode with 68040
@end itemize

@item Intel i386 family
@itemize -
@item Force CPU386
@item Intel i386ex eval board
@item PC-AT i386 and above (go32)
@end itemize

@item PowerPC
@itemize -
@item Papyrus (proprietary controller)
@end itemize

@item SPARC
@itemize -
@item ERC32 (space-hardened V7)
@end itemize

@item MIPS
@itemize -
@item P4000 with R4600 or R4650
@end itemize

@end itemize

Support for the Cygnus NEWLIB Standard C Library is
provided with this release which may be used on any of the RTEMS
supported targets.  The BSPs only provide support for console
I/O only using this library.  Support for the reentrancy
capabilities of newlib is provided in the RTEMS distribution.

@node Development Environment Status Development Environment Status, Development Environment Status Known Problems, Development Environment Status RTEMS Executive Status, Development Environment Status
@section Development Environment Status

This section details the versions of the tools used
to develop and maintain RTEMS @value{VERSION}:

@itemize @bullet
@item Cross Tools
@itemize -
@item gcc - 2.7.2.2 with rtems patch
@item binutils - 2.7 with rtems patch
@item zip - 1.2.4
@item make - 3.74
@end itemize
@end itemize


@node Development Environment Status Known Problems, Executive Problems, Development Environment Status Development Environment Status, Development Environment Status
@section Known Problems
@menu
* Executive Problems::
* Development Environment Problems::
* RTEMS Problem Reporting::
@end menu

Problems which are known to exist at the time of
release are described in the following sections.  These are
provided as warnings to the user and where possible, workarounds
are provided until the problem is corrected.

@node Executive Problems, Development Environment Problems, Development Environment Status Known Problems, Development Environment Status Known Problems
@subsection Executive Problems

There are no known bugs in the executive itself.

@node Development Environment Problems, RTEMS Problem Reporting, Executive Problems, Development Environment Status Known Problems
@subsection Development Environment Problems

There are no known major problems with the
development environment.

@node RTEMS Problem Reporting, RTEMS PROBLEM REPORT, Development Environment Problems, Development Environment Status Known Problems
@subsection RTEMS Problem Reporting

The RTEMS Project uses the GNATS Problem Reporting and Tracking System.
Instructions for reporting a problem are located at
@uref{http://www.rtems.com/bugs.html}.
