-include $(DEVKITARM)/base_rules

CFLAGS	:=	$(BASEFLAGS) $(ARM7FLAGS) $(ARM7INC)
ASFLAGS :=	$(ARM7FLAGS)
VPATH	:=	$(ARM7_VPATH)
DEPSDIR	:=	$(DEPENDS)/arm7

$(LIBDIR)/libnds7.a:	$(ARM7OBJS)

-include $(DEPSDIR)/*.d
