\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename ada_user.info
@setcontentsaftertitlepage
@syncodeindex vr fn
@synindex ky cp
@paragraphindent 0
@c %**end of header

@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@c
@c   Master file for the Ada User's Guide
@c

@c Joel's Questions
@c
@c  1.  Why does paragraphindent only impact makeinfo?
@c  2.  Why does paragraphindent show up in HTML?
@c

@include version.texi
@include common/setup.texi
@include common/rtems.texi

@ifset use-ascii
@dircategory RTEMS On-Line Manual
@direntry
* RTEMS Ada User: (ada_user).          The Ada User's Guide
@end direntry
@end ifset


@c variable substitution info:
@c
@clear is-C
@set is-Ada
@set LANGUAGE Ada
@set STRUCTURE record
@set ROUTINE subprogram
@set OR or
@set RPREFIX RTEMS.
@set DIRPREFIX rtems.
@c the language is @value{LANGUAGE}
@c NOTE:  don't use underscore in the name
@c

@c
@c  Title Page Stuff
@c

@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage RTEMS Applications Ada User's Guide

@setchapternewpage odd
@settitle RTEMS Ada User's Guide
@titlepage
@finalout

@title RTEMS Applications Ada User's Guide
@subtitle Edition @value{EDITION}, for RTEMS @value{VERSION}
@sp 1
@subtitle @value{UPDATED}
@author On-Line Applications Research Corporation
@page
@include common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@contents

@node List of Figures, Preface, Top, Top
@unnumbered List of Figures
@listoffloats Figure

@include user/preface.texi
@include user/overview.texi
@include user/concepts.texi
@include user/datatypes.texi
@include user/init.texi
@include user/task.texi
@include user/intr.texi
@include user/clock.texi
@include user/timer.texi
@include user/sem.texi
@include user/msg.texi
@include user/event.texi
@include user/signal.texi
@include user/part.texi
@include user/region.texi
@include user/dpmem.texi
@include user/io.texi
@include user/fatal.texi
@include user/schedule.texi
@include user/rtmon.texi
@include user/barrier.texi
@include user/bsp.texi
@include user/userext.texi
@include user/conf.texi
@include user/mp.texi
@include user/stackchk.texi
@include user/cpuuse.texi
@include user/object.texi
@include user/chains.texi
@include user/cbs.texi
@include user/dirstat.texi
@include example.texi
@include user/glossary.texi
@node Top, List of Figures, (dir), (dir)
@top RTEMS Applications Ada User's Guide

@menu
* List of Figures::
* Preface::
* Overview::
* Key Concepts::
* RTEMS Data Types::
* Initialization Manager::
* Task Manager::
* Interrupt Manager::
* Clock Manager::
* Timer Manager::
* Semaphore Manager::
* Message Manager::
* Event Manager::
* Signal Manager::
* Partition Manager::
* Region Manager::
* Dual-Ported Memory Manager::
* I/O Manager::
* Fatal Error Manager::
* Scheduling Concepts::
* Rate Monotonic Manager::
* Barrier Manager::
* Board Support Packages::
* User Extensions Manager::
* Configuring a System::
* Multiprocessing Manager::
* Stack Bounds Checker::
* CPU Usage Statistics::
* Object Services::
* Chains::
* Constant Bandwidth Server Scheduler API::
* Directive Status Codes::
* Example Application::
* Glossary::
* Command and Variable Index::
* Concept Index::
@end menu

@node Command and Variable Index, Concept Index, Glossary, Top
@unnumbered Command and Variable Index

@c There are currently no Command and Variable Index entries.

@printindex fn

@node Concept Index, , Command and Variable Index, Top
@unnumbered Concept Index

@c There are currently no Concept Index entries.
@printindex cp

@bye

