@c
@c  COPYRIGHT (c) 1989-2014.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@node Example Application, Glossary, Directive Status Codes STATUS_TEXT - Returns the enumeration name for a status code, Top
@chapter Example Application

@example

Currently there is no example Ada application provided.

@end example
