@c
@c  COPYRIGHT (c) 1989-2014.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@node Example Application, Glossary, Linker Sets RTEMS_LINKER_RWSET_ITEM_ORDERED - Defines an ordered read-write linker set item, Top
@chapter Example Application

@example

Currently there is no example Ada application provided.

@end example
