\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename shell.info
@syncodeindex vr fn
@synindex ky cp
@paragraphindent 0
@c %**end of header

@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@c
@c   Master file for the Shell User's Guide
@c

@c Joel's Questions
@c
@c  1.  Why does paragraphindent only impact makeinfo?
@c  2.  Why does paragraphindent show up in HTML?
@c

@include version.texi
@include common/setup.texi
@include common/rtems.texi

@ifset use-ascii
@dircategory RTEMS Shell On-Line Manual
@direntry
* RTEMS Shell: (shell).              The RTEMS Shell User's Guide.
@end direntry
@end ifset

@c @syncodeindex fn cp

@c
@c  Title Page Stuff
@c

@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage RTEMS Shell User's Guide

@setchapternewpage odd
@settitle RTEMS Shell User's Guide
@titlepage
@finalout

@title RTEMS Shell User's Guide
@subtitle Edition @value{EDITION}, for RTEMS @value{VERSION}
@sp 1
@subtitle @value{UPDATED}
@author On-Line Applications Research Corporation
@page
@include common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@contents

@include preface.texi
@include confinit.texi
@include general.texi
@include file.texi
@include memory.texi
@include rtems.texi
@include network.texi
@node Top, Preface, (dir), (dir)
@top RTEMS Shell User's Guide

@menu
* Preface::
* Configuration and Initialization::
* General Commands::
* File and Directory Commands::
* Memory Commands::
* RTEMS Specific Commands::
* Network Commands::
* Function and Variable Index::
* Concept Index::
* Command Index::
@end menu

@node Function and Variable Index, Concept Index, Network Commands route - show or manipulate the ip routing table, Top
@unnumbered Function and Variable Index
@printindex fn

@c There are currently no Command and Variable Index entries.

@node Concept Index, Command Index, Function and Variable Index, Top
@unnumbered Concept Index
@printindex cp

@node Command Index, , Concept Index, Top
@unnumbered Command Index
@printindex pg

@bye

