\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename filesystem.info
@setcontentsaftertitlepage
@syncodeindex vr fn
@synindex ky cp
@paragraphindent 0
@c %**end of header

@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@c
@c   Master file for the Filesystem Design Guide
@c

@include version.texi
@include common/setup.texi
@include common/rtems.texi

@ifset use-ascii
@dircategory RTEMS On-Line Manual
@direntry
* RTEMS Filesystem Design Guide: (filesystem).
@end direntry
@end ifset

@c
@c  Title Page Stuff
@c

@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage RTEMS Filesystem Design Guide

@setchapternewpage odd
@settitle RTEMS Filesystem Design Guide
@titlepage
@finalout

@title RTEMS Filesystem Design Guide
@subtitle Edition @value{EDITION}, for RTEMS @value{VERSION}
@sp 1
@subtitle @value{UPDATED}
@author On-Line Applications Research Corporation
@page
@include common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@contents

@include preface.texi
@include patheval.texi
@include init.texi
@include mounting.texi
@include syscalls.texi
@include fsrequirements.texi
@include imfs.texi
@include miniimfs.texi
@include tftp.texi
@node Top, Preface, (dir), (dir)
@top RTEMS Filesystem Design Guide

@menu
* Preface::
* Pathname Evaluation::
* System Initialization::
* Mounting and Unmounting Filesystems::
* System Call Development Notes::
* Filesystem Implementation Requirements::
* In-Memory Filesystem::
* Miniature In-Memory Filesystem::
* Trivial FTP Client Filesystem::
* Command and Variable Index::
* Concept Index::
@end menu

@node Command and Variable Index, Concept Index, , Top
@unnumbered Command and Variable Index

There are currently no Command and Variable Index entries.

@c @printindex fn

@node Concept Index, , Command and Variable Index, Top
@unnumbered Concept Index

There are currently no Concept Index entries.
@c @printindex cp

@bye

