\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename networking.info
@setcontentsaftertitlepage
@syncodeindex vr fn
@synindex ky cp
@paragraphindent 0
@c %**end of header

@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@c
@c   Master file for the network Supplement
@c

@include version.texi
@include common/setup.texi
@include common/rtems.texi

@ifset use-ascii
@dircategory RTEMS On-Line Manual
@direntry
* RTEMS Network Supplement: (networking).
@end direntry
@end ifset

@c
@c  Title Page Stuff
@c

@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage RTEMS Network Supplement

@setchapternewpage odd
@settitle RTEMS Network Supplement
@titlepage
@finalout

@title RTEMS Network Supplement
@subtitle Edition @value{EDITION}, for RTEMS @value{VERSION}
@sp 1
@subtitle @value{UPDATED}
@author On-Line Applications Research Corporation
@page
@include common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@contents

@include preface.texi
@include networktasks.texi
@include driver.texi
@include networkapp.texi
@include testing.texi
@include servers.texi
@include decdriver.texi
@node Top, Preface, (dir), (dir)
@top RTEMS TCP/IP Networking Supplement

@menu
* Preface::
* Network Task Structure and Data Flow::
* Networking Driver::
* Using Networking in an RTEMS Application::
* Testing the Driver::
* Network Servers::
* DEC 21140 Driver::
* Command and Variable Index::
* Concept Index::
@end menu

@node Command and Variable Index, Concept Index, List of Ethernet cards using the DEC chip, Top
@unnumbered Command and Variable Index

There are currently no Command and Variable Index entries.

@c @printindex fn

@node Concept Index, , Command and Variable Index, Top
@unnumbered Concept Index

There are currently no Concept Index entries.
@c @printindex cp

@bye

