\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename started_ada.info
@setcontentsaftertitlepage
@syncodeindex vr fn
@synindex ky cp
@paragraphindent 0
@c %**end of header

@c
@c  COPYRIGHT (c) 1988-2002.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.
@c
@c  $Id$
@c

@c
@c   Master file for the Getting Started (C) Guide
@c

@include version.texi
@include common/setup.texi
@include common/rtems.texi

@c
@c  Now set all the tool version dependent information
@c
@include tversions.texi

@ifset use-ascii
@dircategory RTEMS On-Line Manual
@direntry
* Getting Started with GNAT/RTEMS: (started_ada)
@end direntry
@end ifset

@c
@c  Title Page Stuff
@c

@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage Getting Started with RTEMS

@setchapternewpage odd
@settitle Getting Started with GNAT/RTEMS
@titlepage
@finalout

@title Getting Started with GNAT/RTEMS
@subtitle Edition @value{EDITION}, for @value{VERSION}
@sp 1
@subtitle @value{UPDATED}
@author On-Line Applications Research Corporation
@page
@include common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@include intro.texi
@include require.texi
@include buildada.texi
@include buildrt.texi
@include sample.texi
@include gdb.texi

@ifinfo
@node Top, Introduction, (dir), (dir)
@top started_ada

This is the online version of the Getting Started with GNAT/RTEMS.

@menu
* Introduction::
* Requirements::
* Building the GNAT Cross Compiler Toolset::
* Building RTEMS::
* Building the Sample Application::
* Building the GNU Debugger::
@end menu

@c * Command and Variable Index::
@c * Concept Index::
@end ifinfo
@c 
@c 
@c Need to copy the emacs stuff and "trailer stuff" (index, toc) into here
@c

@c @node Command and Variable Index, Concept Index, GDB for DINK32, Top
@c @unnumbered Command and Variable Index

@c There are currently no Command and Variable Index entries.

@c @printindex fn

@c @node Concept Index, , Command and Variable Index, Top
@c @unnumbered Concept Index

@c There are currently no Concept Index entries.
@c @printindex cp

@contents
@bye

