@c
@c  COPYRIGHT (c) 1988-1998.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.
@c
@c  $Id$
@c

@ifinfo
@node Preface, , Top, Top
@end ifinfo
@unnumbered Preface

This is the user's guide for the POSIX API support for RTEMS.

At this point, this is just a basic shell of what this manual
should ultimately be.  

Much of the POSIX API standard is actually implemented in the
newlib ANSI C Library.  Please refer to documentation on
newlib for more information on what it supplies.
