/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _arm7_sha1_homebrew_h_
#define _arm7_sha1_homebrew_h_
//---------------------------------------------------------------------------------
extern const unsigned char arm7_sha1_homebrew[];
extern const int arm7_sha1_homebrew_size;
//---------------------------------------------------------------------------------
#endif //_arm7_sha1_homebrew_h_
//---------------------------------------------------------------------------------
