/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _arm7_sha1_nintendo_h_
#define _arm7_sha1_nintendo_h_
//---------------------------------------------------------------------------------
extern const unsigned char arm7_sha1_nintendo[];
extern const int arm7_sha1_nintendo_size;
//---------------------------------------------------------------------------------
#endif //_arm7_sha1_nintendo_h_
//---------------------------------------------------------------------------------
