# SPDX-License-Identifier: BSD-2-Clause

# Copyright (C) 2026 embedded brains GmbH & Co. KG

name: Find PR by commit
description: |
  Finds the pull request (PR) number associated with a commit.  It works with
  PRs for branches in forked repositories.
inputs:
  repository:
    description: |
      Identifies the repository used for the search.  It shall have an
      `owner/name` format.  The default value is `github.repository`.
    required: false
    default: ${{ github.repository }}
  commit:
    description: |
      Defines the commit to search for.  The default value is
      `github.event.workflow_run.head_sha`.
    required: false
    default: ${{ github.event.workflow_run.head_sha }}
outputs:
  pr:
    description: |
      This is the pull request number associated with the commit.
    value: ${{ steps.pr.outputs.pr }}
runs:
  using: composite
  steps:
    - name: Find PR by commit
      id: pr
      uses: actions/github-script@v7
      env:
        REPOSITORY: ${{ inputs.repository }}
        COMMIT: ${{ inputs.commit }}
      with:
        script: |
          const [owner, repo] = process.env.REPOSITORY.split('/');
          const commit = process.env.COMMIT;
          const pull_requests = await github.rest.pulls.list({
            owner,
            repo,
            state: 'open',
            per_page: 100
          });
          const match = pull_requests.data.find(pr => pr.head.sha === commit);
          if (match) {
            core.info(`PR #${match.number} matches with this workflow run`);
            core.setOutput('pr', match.number);
          } else {
            core.setFailed('No PR is associated with this workflow run');
          }
