\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename afcc
@settitle AFCC Internals Guide
@paragraphindent 0
@c %**end of header

@c
@c  COPYRIGHT (c) 1996-1997.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.
@c

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.
@finalout

@tex
\global\parindent 0in
\global\chapheadingskip = 15pt plus 4pt minus 2pt
\global\secheadingskip = 12pt plus 4pt minus 2pt
\global\subsecheadingskip = 9pt plus 4pt minus 2pt

@ifclear smallbook
\global\parskip 6pt plus 1pt
@end ifclear
@end tex

@ifinfo
@format
START-INFO-DIR-ENTRY
* AFCC: .             AFCC Objects
END-INFO-DIR-ENTRY
@end format
@end ifinfo


@c Joel's Questions
@c
@c  1.  Why does paragraphindent only impact makeinfo?
@c

@setchapternewpage odd

@c
@c   Master file for the C User's Guide
@c
@include Drive.texi
@ifinfo

@node Top, Turret Subsystem, Gunner Station Subsystem, (dir)
@top afcc

This is the info version of the object documentation for the AFCC.

The following subsystems are in the AFCC:

@menu
* Turret Subsystem::
* Vehicle Subsystem::
* Gunner Station Subsystem::
@end menu

@node Turret Subsystem, , Top, Top

The following objects are in the Turret Subsystem:

@menu
* Drive Object::                Drive Object
@end menu

@node Vehicle Subsystem, Gunner Station Subsystem, , Top

@menu
The following objects are in the Turret Subsystem:

* ::
@end menu

@node Gunner Station Subsystem, Top,  Vehicle Subsystem, Top
@menu

The following objects are in the Gunner Station Subsystem:

* ::
@end menu


@end ifinfo
@c 
@c 
@c Need to copy the emacs stuff and "trailer stuff" (index, toc) into here
@c
@bye
