\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename started.info
@setcontentsaftertitlepage
@syncodeindex vr fn
@synindex ky cp
@c @paragraphindent 0
@c %**end of header

@c
@c  COPYRIGHT (c) 1989-2011.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.

@c
@c   Master file for the Getting Started (C) Guide
@c

@include version.texi
@include common/setup.texi
@include common/rtems.texi

@ifset use-ascii
@dircategory RTEMS On-Line Manual
@direntry
* Getting Started with RTEMS: (started).
@end direntry
@end ifset

@c
@c  Title Page Stuff
@c

@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage Getting Started with RTEMS

@setchapternewpage odd
@settitle Getting Started with RTEMS
@titlepage
@finalout

@title Getting Started with RTEMS
@subtitle Edition @value{EDITION}, for @value{VERSION}
@sp 1
@subtitle @value{UPDATED}
@author On-Line Applications Research Corporation
@page
@include common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@contents

@include intro.texi
@include require.texi
@include binaries.texi
@include buildc.texi
@include buildrt.texi
@include sample.texi
@include nextstep.texi
@include nt.texi

@node Top, Introduction, (dir), (dir)
@top Getting Started With RTEMS

This is the online version of the Getting Started with RTEMS.

@menu
* Introduction::
* Requirements::
* Prebuilt Toolset Executables::
* Building the GNU Cross Compiler Toolset::
* Building RTEMS::
* Building the Sample Applications::
* Where To Go From Here::
* Using MS-Windows as a Development Host::
@end menu

@c * Command and Variable Index::
@c * Concept Index::

@c @node Command and Variable Index, Concept Index, Installing GCC AND NEWLIB, Top
@c @unnumbered Command and Variable Index

@c There are currently no Command and Variable Index entries.

@c @printindex fn

@c @node Concept Index, , Command and Variable Index, Top
@c @unnumbered Concept Index

@c There are currently no Concept Index entries.
@c @printindex cp

@bye

