#!/bin/sh 
#
#  Usage: mktoolspec CPU
#

RTEMS_DIR=`dirname $0`

target_alias=$1

# RPM release number
rpm_release=0

# gdb version number
gdb_version=4.18
gdb_patch_version=19991015

# Some linux distributions use /usr/src/packages
# redhat uses /usr/src/redhat
# others might use /usr/src
if test -d /usr/src/packages/SPECS; 
then
dst=/usr/src/packages/SPECS;
elif test -d /usr/src/redhat/SPECS;
 then
dst=/usr/src/redhat/SPECS;
elif test -d /usr/src/SPECS/; 
then
dst=/usr/src/SPECS;
fi

specfile=${dst}/$target_alias-gdb-${gdb_version}.spec

sed -e "s%@Release@%${rpm_release}%g" \
    -e "s%@target_alias@%${target_alias}%g" \
    -e "s%@gdb_version@%${gdb_version}%g" \
    -e "s%@gdb_patch_version@%${gdb_patch_version}%g" \
< ${RTEMS_DIR}/gdb.spec.in \
> ${specfile}

case ${target} in
  powerpc*)
     echo "/opt/rtems/bin/@target_alias@-run" 
     ;;
  sparc*)
     echo "/opt/rtems/bin/@target_alias@-run" 
     echo "/opt/rtems/bin/@target_alias@-sis" 
     ;;
  *) ;;
esac >> ${specfile}

echo Generated ${specfile}.
