#!/bin/sh

#
# A simple shell script to build several rpms in a row.
#
# Used for testing rtems.spec.in
#

# Some linux distributions use /usr/src/packages
# redhat uses /usr/src/redhat
# others might use /usr/src
if test -d /usr/src/packages/SPECS; 
then
dst=/usr/src/packages/SPECS;
elif test -d /usr/src/redhat/SPECS;
 then
dst=/usr/src/redhat/SPECS;
elif test -d /usr/src/SPECS/; 
then
dst=/usr/src/SPECS;
fi

./mkspec pc386 i386-rtems
rpm -ba $dst/rtems-i386-rtems-pc386.spec

./mkspec gensh1 sh-rtemself
rpm -ba $dst/rtems-sh-rtemself-gensh1.spec

./mkspec mcp750 powerpc-rtems
rpm -ba $dst/rtems-powerpc-rtems-mcp750.spec


