\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename hppa1_1.info
@setcontentsaftertitlepage
@syncodeindex vr fn
@synindex ky cp
@paragraphindent 0
@c %**end of header

@c
@c  COPYRIGHT (c) 1988-2002.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.
@c
@c  $Id$
@c

@c
@c   Master file for the Hewlett Packard PA-RISC Applications Supplement
@c

@include version.texi
@include common/setup.texi
@include common/rtems.texi

@ifset use-ascii
@dircategory RTEMS Target Supplements
@direntry
* RTEMS Hewlett Packard PA-RISC Applications Supplement: (hppa1_1).
@end direntry
@end ifset

@c
@c  Title Page Stuff
@c

@c
@c  I don't really like having a short title page.  --joel
@c
@c @shorttitlepage RTEMS Hewlett Packard PA-RISC Applications Supplement 

@setchapternewpage odd
@settitle RTEMS Hewlett Packard PA-RISC Applications Supplement 
@titlepage
@finalout

@title RTEMS Hewlett Packard PA-RISC Applications Supplement 
@subtitle Edition @value{EDITION}, for RTEMS @value{VERSION}
@sp 1
@subtitle @value{UPDATED}
@author On-Line Applications Research Corporation
@page
@include common/cpright.texi
@end titlepage

@c  This prevents a black box from being printed on "overflow" lines.
@c  The alternative is to rework a sentence to avoid this problem.

@include preface.texi
@include cpumodel.texi
@include callconv.texi
@include memmodel.texi
@include intr.texi
@include fatalerr.texi
@include bsp.texi
@include cputable.texi
@include wksheets.texi
@include timing.texi
@include timeSIMHPPA.texi
@ifinfo
@node Top, Preface, (dir), (dir)
@top hppa1_1

This is the online version of the RTEMS Hewlett Packard PA-RISC
Applications Supplement.

@menu
* Preface::
* CPU Model Dependent Features::
* Calling Conventions::
* Memory Model::
* Interrupt Processing::
* Default Fatal Error Processing::
* Board Support Packages::
* Processor Dependent Information Table::
* Memory Requirements::
* Timing Specification::
* HP-7100 Timing Data::
* Command and Variable Index::
* Concept Index::
@end menu

@end ifinfo
@c 
@c 
@c Need to copy the emacs stuff and "trailer stuff" (index, toc) into here
@c

@node Command and Variable Index, Concept Index, HP-7100 Timing Data Directive Times, Top

@unnumbered Command and Variable Index

There are currently no Command and Variable Index entries.

@c @printindex fn

@node Concept Index, , Command and Variable Index, Top
@unnumbered Concept Index

There are currently no Concept Index entries.
@c @printindex cp

@contents
@bye

