@c
@c  COPYRIGHT (c) 1988-2002.
@c  On-Line Applications Research Corporation (OAR).
@c  All rights reserved.
@c
@c  $Id$
@c

@ifinfo
@node Preface, CPU Model Dependent Features, Top, Top
@end ifinfo
@unnumbered Preface

The Real Time Executive for Multiprocessor Systems
(RTEMS) is designed to be portable across multiple processor
architectures.  However, the nature of real-time systems makes
it essential that the application designer understand certain
processor dependent implementation details.  These processor
dependencies include calling convention, board support package
issues, interrupt processing, exact RTEMS memory requirements,
performance data, header files, and the assembly language
interface to the executive.

For information on the PA-RISC V1.1 architecture in
general, refer to the following documents:

@itemize @bullet
@item @cite{PA-RISC 1.1 Architecture and Instruction Set Reference
Manual, Third Edition.  HP Part Number 09740-90039}.
@end itemize

It is highly recommended that the PA-RISC RTEMS
application developer also obtain and become familiar with the
Technical Reference Manual for the particular implementation of
the PA-RISC being used.

